### ISSUE TITLE
Add onClick functionality to the workflow steps

### ISSUE THREAD

**Issue by th4ruka** [tharuka-pavith/workflow-manager#1]
Make the steps in Task.jsx clickable. When user clicks on it, a detailed view should popup.

**Comment by carlykiang** [comment]
Hi! I'm new to open source, and found this via the good first issue tag; would it be alright for me to try this issue?

**Comment by th4ruka** [comment]
The enhancements related to this issue have been merged into the dev branch. The issue can be closed now.

**Comment by th4ruka** [comment]
Issue is closed.
