### ISSUE TITLE
Add click functionality to rows in TODO Tasks page

### ISSUE THREAD

**Issue by th4ruka** [tharuka-pavith/workflow-manager#2]
When a specific row is clicked on the TODO Tasks page, it should navigate to the Task page which shows a detailed workflow of that specific task. 
Also, when a step of that workflow is clicked, it should show a dialog with specific details regarding that step (Use existing TaskDialog.jsx file to implement this)

**Comment by KarthikShetty5** [comment]
Can u assign me this
